---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R * $DEPLOYPATH
    # - /bin/cp -R application $DEPLOYPATH
    # - /bin/cp -R public $DEPLOYPATH
    # - /bin/cp -R system $DEPLOYPATH
    # - /bin/cp .htaccess $DEPLOYPATH
    # - /bin/cp composer.json $DEPLOYPATH
    # - /bin/cp index.php $DEPLOYPATH
    # - /bin/cp license.txt $DEPLOYPATH
    # - /bin/cp .editorconfig $DEPLOYPATH